name: potato_center
description: A new Flutter application.
version: 2.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: any
  page_transition: any
  flutter_svg: ^0.13.0
  android_flutter_updater:
    git:
      url: git://github.com/AgentFabulous/android_flutter_updater
  simple_permissions: any
  http: any
  material_design_icons_flutter: 3.1.3493
  shared_preferences: ^0.5.1+1
  provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - posp.png
    - app-logo.svg
  fonts:
    - family:  Logo
      fonts:
        - asset: fonts/Logo.ttf


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
